title: Kevin Martínez-Folgar, MD, PhD.

theme: jekyll-theme-merlot

name: Kevin Martínez-Folgar, MD, PhD.
description: Physician-Epidemiologist | Health Data Scientist | Health Policy | Global Health Equity

avatar: https://avatars1.githubusercontent.com/u/26907179?s=460&u=e20a764d95a0a1f20a4be6f75a21ee2c387f2169&v=4

footer-links:
  dribbble:
  email: kmfolgar@umich.edu
  facebook:
  flickr:
  github: kmfolgar
  instagram:
  linkedin:
  pinterest:
  rss:
  twitter: kmfolgar
  stackoverflow:
  youtube:
  googleplus:

url: https://kmfolgar.github.io

header_pages:
  - about.md
  - cv.md
  - publications.md
  - appearences.md
  - blog.md
