title: Kevin Martínez-Folgar, MD, PhD
name: Kevin Martínez-Folgar
description: Physician-Epidemiologist focused on chronic disease epidemiology, urban health, and health equity.

theme: jekyll-theme-minimal
url: https://kmfolgar.github.io

email: kmfolgar@umich.edu
github_username: kmfolgar
twitter_username: kmfolgar
orcid: 0000-0001-9262-298X
google_scholar: https://scholar.google.com/citations?user=cAUPpBgAAAAJ
cv_pdf: /cv.pdf
