title: Kevin Martínez-Folgar, MD, PhD
name: Kevin Martínez-Folgar, MD, PhD
description: Physician-Epidemiologist and cancer researcher at the National Cancer Institute (NCI), NIH. Research on cancer disparities, social determinants of health, and urban health.

theme: jekyll-theme-minimal
url: https://kmfolgar.github.io

github_username: kmfolgar
twitter_username: kmfolgar
orcid: 0000-0001-9262-298X
google_scholar: https://scholar.google.com/citations?user=cAUPpBgAAAAJ
contact_url: https://github.com/kmfolgar
